replicaCount: 1

image:
  repository: fairoox94/mi-backend
  tag: "v1"
  pullPolicy: Always

service:
  type: NodePort
  port: 5000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: backend.reservo.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceAccount:
  create: false

autoscaling:
  enabled: false

