replicaCount: 1

image:
  repository: ricardodb/mi-backend
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP # o LoadBalancer si es necesario
  port: 5000

ingress:
  enabled: true # o false si no es necesario
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: backend.reservo.local
      paths:
        - path: /
          pathType: Prefix # Cambio de ImplementationSpecific a Prefix
  tls: []

serviceAccount:
  create: false

autoscaling:
  enabled: false