replicaCount: 1

image:
  repository: ricardodb/mi-frontend
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP #Cambio de LoadBalancer a ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: frontend.reservo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceAccount:
  create: false

autoscaling:
  enabled: false