---
- name: Desplegar app con Helm en Kubernetes (EKS)
  hosts: localhost
  connection: local
  vars:
    docker_image_tag: "{{ DOCKER_IMAGE_TAG }}"
    docker_username: "{{ DOCKER_USERNAME }}"
    aws_access_key_id: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_access_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    aws_session_token: "{{ AWS_SESSION_TOKEN }}"
    aws_region: "us-east-1"
    eks_cluster_name: "mi-cluster-eks"
    namespace: "default" # Define el namespace como una variable

  tasks:
    - name: Configurar AWS CLI (proporcionando credenciales manualmente)
      shell: |
        aws configure set aws_access_key_id {{ aws_access_key_id }}
        aws configure set aws_secret_access_key {{ aws_secret_access_key }}
        aws configure set aws_session_token {{ aws_session_token }}
        aws configure set region {{ aws_region }}

    - name: Actualizar kubeconfig
      shell: |
        aws eks --region {{ aws_region }} update-kubeconfig --name {{ eks_cluster_name }}
      register: kubeconfig_update
      failed_when: kubeconfig_update.rc != 0
      changed_when: true

    - name: Verificar si Helm está instalado
      command: helm version --short
      register: helm_version
      failed_when: helm_version.rc != 0
      changed_when: false
      ignore_errors: true

    - name: Instalar Helm si no está instalado
      apt:
        name: helm
        state: present
      when: helm_version.rc != 0

    - name: Verificar si kubectl está instalado
      command: kubectl version --client=true
      register: kubectl_version
      failed_when: kubectl_version.rc != 0
      changed_when: false
      ignore_errors: true

    - name: Instalar kubectl si no está instalado
      apt:
        name: kubectl
        state: present
      when: kubectl_version.rc != 0

    - name: Desplegar backend con Helm
      shell: |
        cd .. && helm upgrade --install backend ./kubernetes/backend/backend-chart --namespace {{ namespace }} --set image.repository={{ docker_username }}/mi-backend --set image.tag={{ docker_image_tag }}
      register: backend_deploy
      retries: 3
      delay: 10
      until: backend_deploy.rc == 0

    - name: Mostrar log de helm backend
      debug:
        msg: "{{ backend_deploy }}"

    - name: Verificar si hubo errores en la instalación del chart backend
      fail:
        msg: "Error en la instalación del chart backend"
      when: backend_deploy.rc != 0

    - name: Desplegar frontend con Helm
      shell: |
        cd .. && helm upgrade --install frontend ./kubernetes/frontend/frontend-chart --namespace {{ namespace }} --set image.repository={{ docker_username }}/mi-frontend --set image.tag={{ docker_image_tag }}
      register: frontend_deploy
      retries: 3
      delay: 10
      until: frontend_deploy.rc == 0

    - name: Mostrar log de helm frontend
      debug:
        msg: "{{ frontend_deploy }}"

    - name: Verificar si hubo errores en la instalación del chart frontend
      fail:
        msg: "Error en la instalación del chart frontend"
      when: frontend_deploy.rc != 0

    - name: Verificar existencia del deployment backend
      shell: |
        kubectl get deployment/backend-backend-chart -n {{ namespace }}
      register: backend_deployment_exists
      failed_when: backend_deployment_exists.rc != 0

    - name: Verificar estado del rollout del deployment backend
      shell: |
        kubectl rollout status deployment/backend-backend-chart -n {{ namespace }}
      register: backend_rollout_status
      failed_when: backend_rollout_status.rc != 0

    - name: Mostrar log de backend rollout
      debug:
        msg: "{{ backend_rollout_status }}"

    - name: Verificar existencia del deployment frontend
      shell: |
        kubectl get deployment/frontend-frontend-chart -n {{ namespace }}
      register: frontend_deployment_exists
      failed_when: frontend_deployment_exists.rc != 0

    - name: Verificar estado del rollout del deployment frontend
      shell: |
        kubectl rollout status deployment/frontend-frontend-chart -n {{ namespace }}
      register: frontend_rollout_status
      failed_when: frontend_rollout_status.rc != 0

    - name: Mostrar log de frontend rollout
      debug:
        msg: "{{ frontend_rollout_status }}"

    - name: Obtener logs de pods del backend
      shell: |
        kubectl get pods -n {{ namespace }} -l app=backend -o name | xargs kubectl logs -n {{ namespace }}
      register: backend_pod_logs
      ignore_errors: true

    - name: Mostrar logs de pods del backend
      debug:
        msg: "{{ backend_pod_logs.stdout_lines }}"

    - name: Obtener eventos de pods del backend
      shell: |
        kubectl get pods -n {{ namespace }} -l app=backend -o name | xargs kubectl describe pod -n {{ namespace }}
      register: backend_pod_events
      ignore_errors: true

    - name: Mostrar eventos de pods del backend
      debug:
        msg: "{{ backend_pod_events.stdout_lines }}"

    - name: Obtener logs de pods del frontend
      shell: |
        kubectl get pods -n {{ namespace }} -l app=frontend -o name | xargs kubectl logs -n {{ namespace }}
      register: frontend_pod_logs
      ignore_errors: true

    - name: Mostrar logs de pods del frontend
      debug:
        msg: "{{ frontend_pod_logs.stdout_lines }}"

    - name: Obtener eventos de pods del frontend
      shell: |
        kubectl get pods -n {{ namespace }} -l app=frontend -o name | xargs kubectl describe pod -n {{ namespace }}
      register: frontend_pod_events
      ignore_errors: true

    - name: Mostrar eventos de pods del frontend
      debug:
        msg: "{{ frontend_pod_events.stdout_lines }}"