---
- name: Desplegar app con Helm en EKS
  hosts: localhost
  connection: local
  vars:
    docker_image_tag: "{{ DOCKER_IMAGE_TAG }}"
  tasks:
    - name: Desplegar backend con Helm
      shell: |
        helm upgrade --install backend ./helm/backend \
          --namespace default \
          --set image.repository=${DOCKER_USERNAME}/mi-backend \
          --set image.tag={{ docker_image_tag }}

    - name: Desplegar frontend con Helm
      shell: |
        helm upgrade --install frontend ./helm/frontend \
          --namespace default \
          --set image.repository=${DOCKER_USERNAME}/mi-frontend \
          --set image.tag={{ docker_image_tag }}

    - name: Esperar a que los deployments estén listos
      shell: |
        kubectl rollout status deployment/frontend -n default
        kubectl rollout status deployment/backend -n default
      register: result
      until: result.rc == 0
      retries: 5
      delay: 30
